version: 2
updates:
  - directory: /
    labels:
      - 🌋 technical debt
    package-ecosystem: github-actions
    schedule:
      interval: monthly
  - directory: /
    labels:
      - 🌋 technical debt
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/dev-image
    labels:
      - 🌋 technical debt
    package-ecosystem: docker
    schedule:
      interval: monthly
  - directory: /packages/dev-image
    labels:
      - 🌋 technical debt
    package-ecosystem: docker
    schedule:
      interval: monthly
  - directory: /packages/eslint-config
    labels:
      - 🌋 technical debt
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/npm-package-json-lint-config
    labels:
      - 🌋 technical debt
    package-ecosystem: npm
    schedule:
      interval: monthly
