version: 2
updates:
  - directory: /
    labels:
      - 🔧 maintenance
    package-ecosystem: github-actions
    schedule:
      interval: monthly
  - directory: /
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/commitlint-config
    labels:
      - 🔧 maintenance
    package-ecosystem: docker
    schedule:
      interval: monthly
  - directory: /packages/dev-image
    labels:
      - 🔧 maintenance
    package-ecosystem: docker
    schedule:
      interval: monthly
  - directory: /packages/eslint-config
    ignore:
      - dependency-name: graphql
        update-types:
          - version-update:semver-major
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/npm-package-json-lint-config
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/prettier-config
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/pulumi-policy-pack
    labels:
      - 🔧 maintenance
    package-ecosystem: npm
    schedule:
      interval: monthly
  - directory: /packages/ruff-config
    labels:
      - 🔧 maintenance
    package-ecosystem: pip
    schedule:
      interval: monthly
