[project]
name = "spear-ai-sqlfluff-config"
version = "2.0.1"
description = "Spear AI SQLFluff config"
authors = [{ name = "Spear AI", email = "org@spear.ai" }]
keywords = [
  "ai",
  "config",
  "SQLFluff",
  "spear"
]
requires-python = ">=3.10,<3.13"
dependencies = [
  "sqlfluff==3.0.6"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
