[tool.poetry]
name = "spear-ai-sqlfluff-config"
version = "1.0.0"
description = "Spear AI Ruff config"
authors = ["Spear AI <org@spear.ai>"]
keywords = [
  "ai",
  "config",
  "SQLFluff",
  "spear"
]
packages = [{ include = "spear_ai_sqlfluff_config" }]
readme = "README.md"
repository = "https://github.com/spear-ai/citizen"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
sqlfluff = "^3.0.6"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
