[project]
name = "spear-ai-sqlfluff-config"
version = "2.0.2"
description = "Spear AI’s SQLFluff config"
authors = [{ name = "Spear AI", email = "org@spear.ai" }]
keywords = [
  "SQLFluff",
  "Spear AI",
  "config",
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "sqlfluff==3.0.6"
]

[project.urls]
Changelog = "https://github.com/spear-ai/citizen/tree/main/packages/sqlfluff-config/CHANGELOG.md"
Documentation = "https://github.com/spear-ai/citizen/tree/main/packages/sqlfluff-config"
Repository = "https://github.com/spear-ai/citizen.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
