import { fileURLToPath } from "node:url";
import { Alphabet } from "eslint-plugin-perfectionist/alphabet";
import { defineConfig } from "oxlint";

// Oxlint resolves `jsPlugins` from the consuming configuration file, so each plugin is resolved
// from this package's own dependencies and keeps the name ESLint would derive from its package.
const resolvePlugin = (packageName: string) => ({
  name: packageName.replace(/^(?<scope>@[^/]+\/)?eslint-plugin-?/u, "$<scope>").replace(/\/$/u, ""),
  specifier: fileURLToPath(import.meta.resolve(packageName)),
});

// Sorts type members by character code, so uppercase keys come before lowercase ones. The range
// stops below the surrogate block because Oxlint passes rule options to plugins as JSON.
const characterCodeSortOptions = {
  alphabet: Alphabet.generateFrom(
    Array.from({ length: 0xd8_00 }, (_, codePoint) => String.fromCodePoint(codePoint)),
  )
    .sortByCharCodeAt()
    .getCharacters(),
  ignoreCase: false,
  type: "custom",
} as const;

// eslint-disable-next-line import/no-default-export
export default defineConfig({
  plugins: ["import", "jsx-a11y", "nextjs", "promise", "react", "typescript", "unicorn"],
  env: {
    builtin: true,
  },
  ignorePatterns: [
    "**/*.d.ts",
    "**/__generated__/**",
    "**/persisted-queries.json",
    "**/.coverage_reports",
    "**/.gmrc.cjs",
    "**/.mypy_cache",
    "**/.next",
    "**/.pytest_cache",
    "**/.ruff_cache",
    "**/.turbo/**",
    "**/.venv",
    "**/.yarn/**",
    "**/build",
    "**/dist",
    "**/htmlcov/**",
    "**/node_modules",
    "**/playwright-report/**",
    "**/pyproject.toml",
    "**/test-results/**",
    "**/third_party/**",
    ".cursor/**",
    ".turbo",
    ".turbo/**",
    ".vercel/**",
    "package-lock.json",
    "pnpm-lock.yaml",
  ],
  rules: {},
  overrides: [
    {
      files: [
        "**/*.cjs",
        "**/*.js",
        "**/*.jsx",
        "**/*.mjs",
        "**/*.d.ts",
        "**/*.cts",
        "**/*.mts",
        "**/*.ts",
        "**/*.tsx",
      ],
      rules: {
        "accessor-pairs": "off",
        "array-callback-return": [
          "error",
          {
            allowImplicit: true,
          },
        ],
        "block-scoped-var": "error",
        complexity: ["off", 20],
        "class-methods-use-this": [
          "error",
          {
            exceptMethods: [
              "render",
              "getInitialState",
              "getDefaultProps",
              "getChildContext",
              "componentWillMount",
              "UNSAFE_componentWillMount",
              "componentDidMount",
              "componentWillReceiveProps",
              "UNSAFE_componentWillReceiveProps",
              "shouldComponentUpdate",
              "componentWillUpdate",
              "UNSAFE_componentWillUpdate",
              "componentDidUpdate",
              "componentWillUnmount",
              "componentDidCatch",
              "getSnapshotBeforeUpdate",
            ],
          },
        ],
        "default-case": [
          "error",
          {
            commentPattern: "^no default$",
          },
        ],
        "default-case-last": "error",
        "default-param-last": "off",
        eqeqeq: [
          "error",
          "always",
          {
            null: "ignore",
          },
        ],
        "grouped-accessor-pairs": "error",
        "guard-for-in": "error",
        "max-classes-per-file": ["error", 1],
        "no-alert": "warn",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-constructor-return": "error",
        "no-div-regex": "off",
        "no-else-return": [
          "error",
          {
            allowElseIf: false,
          },
        ],
        "no-empty-function": [
          "error",
          {
            allow: ["arrowFunctions"],
          },
        ],
        "no-empty-pattern": "error",
        "no-eq-null": "off",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-fallthrough": "error",
        "no-global-assign": [
          "error",
          {
            exceptions: [],
          },
        ],
        "no-implicit-coercion": [
          "off",
          {
            boolean: false,
            number: true,
            string: true,
            allow: [],
          },
        ],
        "no-iterator": "error",
        "no-labels": [
          "error",
          {
            allowLoop: false,
            allowSwitch: false,
          },
        ],
        "no-lone-blocks": "error",
        "no-loop-func": "off",
        "no-magic-numbers": "off",
        "no-multi-str": "error",
        "no-new": "error",
        "no-new-func": "off",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-param-reassign": [
          "error",
          {
            props: true,
            ignorePropertyModificationsFor: [
              "acc",
              "accumulator",
              "e",
              "ctx",
              "context",
              "req",
              "request",
              "res",
              "response",
              "$scope",
              "staticContext",
            ],
          },
        ],
        "no-proto": "error",
        "no-redeclare": "off",
        "no-return-assign": ["error", "always"],
        "no-script-url": "error",
        "no-self-assign": [
          "error",
          {
            props: true,
          },
        ],
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-throw-literal": "off",
        "no-unmodified-loop-condition": "off",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-useless-call": "off",
        "no-useless-catch": "error",
        "no-useless-concat": "error",
        "no-useless-escape": "error",
        "no-useless-return": "error",
        "no-void": ["error", { allowAsStatement: true }],
        "no-warning-comments": [
          "off",
          {
            terms: ["todo", "fixme", "xxx"],
            location: "start",
          },
        ],
        "no-with": "off",
        "prefer-promise-reject-errors": "off",
        radix: "error",
        "require-await": "off",
        "vars-on-top": "error",
        yoda: "error",
        "consistent-return": "error",
        "global-require": "error",
        "no-new-require": "error",
        "no-path-concat": "error",
        "for-direction": "error",
        "getter-return": "off",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": ["error", "always"],
        "no-console": "warn",
        "no-constant-condition": "warn",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "off",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "off",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "off",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "off",
        "no-misleading-character-class": "error",
        "no-obj-calls": "off",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-regex-spaces": "error",
        "no-setter-return": "off",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-unreachable": "off",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": [
          "error",
          {
            disallowArithmeticOperators: true,
          },
        ],
        "no-unused-private-class-members": "off",
        "no-useless-backreference": "off",
        "use-isnan": "error",
        "valid-typeof": [
          "error",
          {
            requireStringLiterals: true,
          },
        ],
        "capitalized-comments": [
          "warn",
          "always",
          {
            ignoreConsecutiveComments: true,
          },
        ],
        "func-names": "warn",
        "func-style": ["error", "expression"],
        "id-length": "off",
        "max-depth": ["off", 4],
        "max-lines": [
          "off",
          {
            max: 300,
            skipBlankLines: true,
            skipComments: true,
          },
        ],
        "max-lines-per-function": [
          "off",
          {
            max: 50,
            skipBlankLines: true,
            skipComments: true,
            IIFEs: true,
          },
        ],
        "max-nested-callbacks": "off",
        "max-params": ["off", 3],
        "max-statements": ["off", 10],
        "new-cap": [
          "error",
          {
            newIsCap: true,
            newIsCapExceptions: [],
            capIsNew: false,
            capIsNewExceptions: ["Immutable.Map", "Immutable.Set", "Immutable.List"],
          },
        ],
        "no-array-constructor": "error",
        "no-bitwise": "error",
        "no-continue": ["off"],
        "no-inline-comments": "off",
        "no-lonely-if": "error",
        "no-multi-assign": ["error"],
        "no-negated-condition": "off",
        "no-nested-ternary": "off",
        "no-plusplus": "error",
        "no-ternary": "off",
        "no-unneeded-ternary": [
          "error",
          {
            defaultAssignment: false,
          },
        ],
        "operator-assignment": ["error", "always"],
        "prefer-exponentiation-operator": "error",
        "prefer-object-spread": "error",
        "sort-keys": [
          "off",
          "asc",
          {
            caseSensitive: false,
            natural: true,
          },
        ],
        "sort-vars": ["error"],
        "unicode-bom": ["error", "never"],
        "init-declarations": "off",
        "no-delete-var": "error",
        "no-label-var": "error",
        "no-restricted-globals": [
          "error",
          {
            name: "isFinite",
            message:
              "Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite",
          },
          {
            name: "isNaN",
            message: "Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan",
          },
          "addEventListener",
          "blur",
          "close",
          "closed",
          "confirm",
          "defaultStatus",
          "defaultstatus",
          "event",
          "external",
          "find",
          "focus",
          "frameElement",
          "frames",
          "history",
          "innerHeight",
          "innerWidth",
          "length",
          "location",
          "locationbar",
          "menubar",
          "moveBy",
          "moveTo",
          "name",
          "onblur",
          "onerror",
          "onfocus",
          "onload",
          "onresize",
          "onunload",
          "open",
          "opener",
          "opera",
          "outerHeight",
          "outerWidth",
          "pageXOffset",
          "pageYOffset",
          "parent",
          "print",
          "removeEventListener",
          "resizeBy",
          "resizeTo",
          "screen",
          "screenLeft",
          "screenTop",
          "screenX",
          "screenY",
          "scroll",
          "scrollbars",
          "scrollBy",
          "scrollTo",
          "scrollX",
          "scrollY",
          "self",
          "status",
          "statusbar",
          "stop",
          "toolbar",
          "top",
        ],
        "no-shadow": "off",
        "no-shadow-restricted-names": "error",
        "no-undef": "off",
        "no-undefined": "off",
        "no-unused-vars": "error",
        "arrow-body-style": [
          "error",
          "as-needed",
          {
            requireReturnForObjectLiteral: false,
          },
        ],
        "constructor-super": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-duplicate-imports": "off",
        "no-restricted-imports": [
          "off",
          {
            paths: [],
            patterns: [],
          },
        ],
        "no-this-before-super": "off",
        "no-useless-computed-key": "error",
        "no-useless-constructor": "error",
        "no-useless-rename": [
          "error",
          {
            ignoreDestructuring: false,
            ignoreImport: false,
            ignoreExport: false,
          },
        ],
        "no-var": "error",
        "prefer-const": "error",
        "prefer-destructuring": [
          "error",
          {
            VariableDeclarator: {
              array: false,
              object: true,
            },
            AssignmentExpression: {
              array: true,
              object: false,
            },
          },
          {
            enforceForRenamedProperties: false,
          },
        ],
        "prefer-numeric-literals": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "error",
        "require-yield": "error",
        "sort-imports": [
          "off",
          {
            ignoreCase: false,
            ignoreDeclarationSort: false,
            ignoreMemberSort: false,
            memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
          },
        ],
        "symbol-description": "error",
        "react/display-name": [
          "off",
          {
            ignoreTranspilerName: false,
          },
        ],
        "react/jsx-boolean-value": [
          "error",
          "never",
          {
            always: [],
          },
        ],
        "react/jsx-handler-names": [
          "off",
          {
            eventHandlerPrefix: "handle",
            eventHandlerPropPrefix: "on",
          },
        ],
        "react/jsx-key": "off",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-undef": "error",
        "react/jsx-pascal-case": [
          "error",
          {
            allowAllCaps: true,
            ignore: [],
          },
        ],
        "react/no-danger": "warn",
        "react/no-did-mount-set-state": "off",
        "react/no-will-update-set-state": "error",
        "react/no-direct-mutation-state": "off",
        "react/no-is-mounted": "error",
        "react/no-multi-comp": "off",
        "react/no-set-state": "off",
        "react/no-string-refs": "error",
        "react/no-unknown-property": "error",
        "react/prefer-es6-class": ["error", "always"],
        "react/require-render-return": "error",
        "react/self-closing-comp": "error",
        "react/jsx-no-target-blank": [
          "error",
          {
            enforceDynamicLinks: "always",
          },
        ],
        "react/jsx-filename-extension": [
          "error",
          {
            extensions: [".jsx", ".tsx"],
          },
        ],
        "react/jsx-no-comment-textnodes": "error",
        "react/no-render-return-value": "error",
        "react/no-find-dom-node": "error",
        "react/forbid-elements": [
          "off",
          {
            forbid: [],
          },
        ],
        "react/no-danger-with-children": "error",
        "react/no-unescaped-entities": "error",
        "react/no-children-prop": "error",
        "react/no-array-index-key": "error",
        "react/void-dom-elements-no-children": "error",
        "react/no-redundant-should-component-update": "error",
        "react/jsx-curly-brace-presence": [
          "error",
          {
            props: "never",
            children: "never",
          },
        ],
        "react/button-has-type": [
          "error",
          {
            button: true,
            submit: true,
            reset: false,
          },
        ],
        "react/forbid-dom-props": [
          "error",
          {
            forbid: [
              {
                message: "Use the `className` property instead",
                propName: "style",
              },
            ],
          },
        ],
        "react/no-this-in-sfc": "error",
        "react/jsx-max-depth": "off",
        "react/style-prop-object": ["off"],
        "react/no-unsafe": "off",
        "react/jsx-fragments": ["error", "syntax"],
        "react/state-in-constructor": ["error", "always"],
        "react/jsx-props-no-spreading": [
          "error",
          {
            html: "enforce",
            custom: "enforce",
            explicitSpread: "ignore",
            exceptions: [],
          },
        ],
        "react/jsx-no-script-url": [
          "error",
          [
            {
              name: "Link",
              props: ["to"],
            },
          ],
        ],
        "react/jsx-no-useless-fragment": "error",
        "react/jsx-no-constructed-context-values": "error",
        "react/no-namespace": "error",
        // TODO: react/no-deprecated: not yet implemented in oxlint
        // TODO: react/no-typos: not yet implemented in oxlint
        "jsx-a11y/alt-text": [
          "error",
          {
            elements: ["img", "object", "area", 'input[type="image"]'],
            img: [],
            object: [],
            area: [],
            'input[type="image"]': [],
          },
        ],
        "jsx-a11y/anchor-has-content": "error",
        "jsx-a11y/anchor-is-valid": [
          "error",
          {
            aspects: ["invalidHref", "preferButton"],
            components: ["Link"],
            specialLink: ["hrefLeft", "hrefRight"],
          },
        ],
        "jsx-a11y/aria-activedescendant-has-tabindex": "error",
        "jsx-a11y/aria-props": "error",
        "jsx-a11y/aria-proptypes": "error",
        "jsx-a11y/aria-role": [
          "error",
          {
            ignoreNonDOM: false,
          },
        ],
        "jsx-a11y/aria-unsupported-elements": "error",
        "jsx-a11y/autocomplete-valid": [
          "off",
          {
            inputComponents: [],
          },
        ],
        "jsx-a11y/click-events-have-key-events": "error",
        "jsx-a11y/heading-has-content": [
          "error",
          {
            components: [""],
          },
        ],
        "jsx-a11y/html-has-lang": "error",
        "jsx-a11y/iframe-has-title": "error",
        "jsx-a11y/img-redundant-alt": "error",
        "jsx-a11y/label-has-associated-control": [
          "error",
          {
            assert: "either",
          },
        ],
        "jsx-a11y/lang": "error",
        "jsx-a11y/media-has-caption": [
          "error",
          {
            audio: [],
            video: [],
            track: [],
          },
        ],
        "jsx-a11y/mouse-events-have-key-events": "error",
        "jsx-a11y/no-access-key": "error",
        "jsx-a11y/no-autofocus": ["off"],
        "jsx-a11y/no-distracting-elements": [
          "error",
          {
            elements: ["marquee", "blink"],
          },
        ],
        "jsx-a11y/no-noninteractive-tabindex": [
          "error",
          {
            tags: [],
            roles: ["tabpanel"],
          },
        ],
        "jsx-a11y/no-redundant-roles": "error",
        "jsx-a11y/no-static-element-interactions": [
          "error",
          {
            handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress", "onKeyDown", "onKeyUp"],
          },
        ],
        "jsx-a11y/role-has-required-aria-props": "error",
        "jsx-a11y/role-supports-aria-props": "error",
        "jsx-a11y/scope": "error",
        "jsx-a11y/tabindex-no-positive": "error",
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "error",
        "no-new-native-nonconstructor": "off",
        "typescript/adjacent-overload-signatures": "error",
        "typescript/array-type": "error",
        "typescript/ban-tslint-comment": "error",
        "typescript/class-literal-property-style": "error",
        "typescript/consistent-generic-constructors": "error",
        "typescript/consistent-indexed-object-style": "error",
        "typescript/consistent-type-assertions": "error",
        "typescript/consistent-type-definitions": ["error", "type"],
        "typescript/no-confusing-non-null-assertion": "error",
        "typescript/no-inferrable-types": "error",
        "typescript/non-nullable-type-assertion-style": "error",
        "typescript/prefer-for-of": "error",
        "typescript/prefer-function-type": "error",
        "typescript/prefer-includes": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "typescript/prefer-optional-chain": "error",
        "typescript/await-thenable": "error",
        "typescript/ban-ts-comment": [
          "error",
          {
            minimumDescriptionLength: 10,
          },
        ],
        "typescript/no-array-delete": "error",
        "typescript/no-base-to-string": "error",
        "typescript/no-confusing-void-expression": "error",
        "typescript/no-deprecated": "error",
        "typescript/no-duplicate-enum-values": "error",
        "typescript/no-duplicate-type-constituents": "error",
        "typescript/no-dynamic-delete": "error",
        "typescript/no-empty-object-type": "error",
        "typescript/no-explicit-any": "error",
        "typescript/no-extra-non-null-assertion": "error",
        "typescript/no-extraneous-class": "error",
        "typescript/no-floating-promises": "error",
        "typescript/no-for-in-array": "error",
        "typescript/no-implied-eval": "error",
        "typescript/no-invalid-void-type": "error",
        "typescript/no-meaningless-void-operator": "error",
        "typescript/no-misused-new": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-misused-spread": "error",
        "typescript/no-mixed-enums": "error",
        "typescript/no-namespace": "error",
        "typescript/no-non-null-asserted-nullish-coalescing": "error",
        "typescript/no-non-null-asserted-optional-chain": "error",
        "typescript/no-non-null-assertion": "error",
        "typescript/no-redundant-type-constituents": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-this-alias": "error",
        "typescript/no-unnecessary-boolean-literal-compare": "error",
        "typescript/no-unnecessary-condition": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unnecessary-type-arguments": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-declaration-merging": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-unsafe-unary-minus": "error",
        "typescript/no-wrapper-object-types": "error",
        "typescript/only-throw-error": "error",
        "typescript/prefer-as-const": "error",
        "typescript/prefer-literal-enum-member": "error",
        "typescript/prefer-namespace-keyword": "error",
        "typescript/prefer-promise-reject-errors": "error",
        "typescript/prefer-reduce-type-parameter": "error",
        "typescript/prefer-return-this-type": "error",
        "typescript/related-getter-setter-pairs": "error",
        "typescript/require-await": "error",
        "typescript/restrict-plus-operands": [
          "error",
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        "typescript/restrict-template-expressions": [
          "error",
          {
            allowBoolean: true,
            allowNumber: true,
          },
        ],
        "typescript/return-await": ["error", "error-handling-correctness-only"],
        "typescript/triple-slash-reference": "error",
        "typescript/unbound-method": "error",
        "typescript/unified-signatures": "error",
        "typescript/use-unknown-in-catch-callback-variable": "error",
        "typescript/dot-notation": "error",
        "typescript/no-array-constructor": "error",
        "typescript/no-empty-function": [
          "error",
          {
            allow: ["arrowFunctions"],
          },
        ],
        "typescript/no-unnecessary-type-conversion": "error",
        "typescript/no-unnecessary-type-parameters": "error",
        "typescript/no-unused-expressions": "error",
        "typescript/no-unused-vars": "error",
        "typescript/no-useless-constructor": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/prefer-find": "error",
        "typescript/prefer-regexp-exec": "error",
        "typescript/prefer-string-starts-ends-with": "error",
        "@eslint-community/eslint-comments/disable-enable-pair": [
          "error",
          {
            allowWholeFile: true,
          },
        ],
        "@eslint-community/eslint-comments/no-aggregating-enable": "error",
        "@eslint-community/eslint-comments/no-duplicate-disable": "error",
        "@eslint-community/eslint-comments/no-unlimited-disable": "error",
        "@eslint-community/eslint-comments/no-unused-enable": "error",
        "import/named": "off",
        "import/namespace": "error",
        "import/default": "error",
        "import/export": "error",
        "import/no-named-as-default": "warn",
        "import/no-named-as-default-member": "warn",
        "import/no-duplicates": "warn",
        "regexp/confusing-quantifier": "warn",
        "regexp/control-character-escape": "error",
        "regexp/grapheme-string-literal": "error",
        "regexp/hexadecimal-escape": "error",
        "regexp/letter-case": "error",
        "regexp/match-any": "error",
        "regexp/negation": "error",
        "regexp/no-contradiction-with-assertion": "error",
        "regexp/no-control-character": "error",
        "regexp/no-dupe-characters-character-class": "error",
        "regexp/no-dupe-disjunctions": "error",
        "regexp/no-empty-alternative": "warn",
        "regexp/no-empty-capturing-group": "error",
        "regexp/no-empty-character-class": "error",
        "regexp/no-empty-group": "error",
        "regexp/no-empty-lookarounds-assertion": "error",
        "regexp/no-empty-string-literal": "error",
        "regexp/no-escape-backspace": "error",
        "regexp/no-extra-lookaround-assertions": "error",
        "regexp/no-invalid-regexp": "error",
        "regexp/no-invisible-character": "error",
        "regexp/no-lazy-ends": "warn",
        "regexp/no-legacy-features": "error",
        "regexp/no-misleading-capturing-group": "error",
        "regexp/no-misleading-unicode-character": "error",
        "regexp/no-missing-g-flag": "error",
        "regexp/no-non-standard-flag": "error",
        "regexp/no-obscure-range": "error",
        "regexp/no-octal": "error",
        "regexp/no-optional-assertion": "error",
        "regexp/no-potentially-useless-backreference": "warn",
        "regexp/no-standalone-backslash": "error",
        "regexp/no-super-linear-backtracking": "error",
        "regexp/no-super-linear-move": "error",
        "regexp/no-trivially-nested-assertion": "error",
        "regexp/no-trivially-nested-quantifier": "error",
        "regexp/no-unused-capturing-group": "error",
        "regexp/no-useless-assertions": "error",
        "regexp/no-useless-backreference": "error",
        "regexp/no-useless-character-class": "error",
        "regexp/no-useless-dollar-replacements": "error",
        "regexp/no-useless-escape": "error",
        "regexp/no-useless-flag": "warn",
        "regexp/no-useless-lazy": "error",
        "regexp/no-useless-non-capturing-group": "error",
        "regexp/no-useless-quantifier": "error",
        "regexp/no-useless-range": "error",
        "regexp/no-useless-set-operand": "error",
        "regexp/no-useless-string-literal": "error",
        "regexp/no-useless-two-nums-quantifier": "error",
        "regexp/no-zero-quantifier": "error",
        "regexp/optimal-lookaround-quantifier": "warn",
        "regexp/optimal-quantifier-concatenation": "error",
        "regexp/prefer-character-class": "error",
        "regexp/prefer-d": "error",
        "regexp/prefer-escape-replacement-dollar-char": "error",
        "regexp/prefer-lookaround": "error",
        "regexp/prefer-named-backreference": "error",
        "regexp/prefer-named-capture-group": "error",
        "regexp/prefer-named-replacement": "error",
        "regexp/prefer-plus-quantifier": "error",
        "regexp/prefer-predefined-assertion": "error",
        "regexp/prefer-quantifier": "error",
        "regexp/prefer-question-quantifier": "error",
        "regexp/prefer-range": "error",
        "regexp/prefer-regexp-exec": "error",
        "regexp/prefer-regexp-test": "error",
        "regexp/prefer-result-array-groups": "error",
        "regexp/prefer-set-operation": "error",
        "regexp/prefer-star-quantifier": "error",
        "regexp/prefer-unicode-codepoint-escapes": "error",
        "regexp/prefer-w": "error",
        "regexp/require-unicode-regexp": "error",
        "regexp/require-unicode-sets-regexp": "off",
        "regexp/simplify-set-operations": "error",
        "regexp/sort-alternatives": "error",
        "regexp/sort-character-class-elements": "error",
        "regexp/sort-flags": "error",
        "regexp/strict": "error",
        "regexp/unicode-escape": "error",
        "regexp/unicode-property": "error",
        "regexp/use-ignore-case": "error",
        "promise/always-return": "error",
        "promise/no-return-wrap": "error",
        "promise/param-names": "error",
        "promise/catch-or-return": "error",
        "promise/no-nesting": "warn",
        "promise/no-promise-in-callback": "warn",
        "promise/no-callback-in-promise": "warn",
        "promise/avoid-new": "off",
        "promise/no-new-statics": "error",
        "promise/no-return-in-finally": "warn",
        "promise/valid-params": "warn",
        "sonarjs/cognitive-complexity": ["off"],
        "sonarjs/elseif-without-else": "off",
        "sonarjs/max-switch-cases": "error",
        "sonarjs/no-all-duplicated-branches": "error",
        "sonarjs/no-collapsible-if": "error",
        "sonarjs/no-collection-size-mischeck": "error",
        "sonarjs/no-duplicate-string": ["off"],
        "sonarjs/no-duplicated-branches": "error",
        "sonarjs/no-element-overwrite": "error",
        "sonarjs/no-empty-collection": "error",
        "sonarjs/no-extra-arguments": "error",
        "sonarjs/no-gratuitous-expressions": "error",
        "sonarjs/no-identical-conditions": "error",
        "sonarjs/no-identical-expressions": "error",
        "sonarjs/no-identical-functions": "error",
        "sonarjs/no-ignored-return": "error",
        "sonarjs/no-inverted-boolean-check": "error",
        "sonarjs/no-nested-switch": "error",
        "sonarjs/no-nested-template-literals": "error",
        "sonarjs/no-redundant-boolean": "error",
        "sonarjs/no-redundant-jump": "error",
        "sonarjs/no-same-line-conditional": "error",
        "sonarjs/no-small-switch": "error",
        "sonarjs/no-unused-collection": "error",
        "sonarjs/no-use-of-empty-return-value": "error",
        "sonarjs/no-useless-catch": "error",
        "sonarjs/non-existent-operator": "error",
        "sonarjs/prefer-immediate-return": "error",
        "sonarjs/prefer-object-literal": "error",
        "sonarjs/prefer-single-boolean-return": "error",
        "sonarjs/prefer-while": "error",
        "perfectionist/sort-enums": ["error", characterCodeSortOptions],
        "perfectionist/sort-interfaces": ["error", characterCodeSortOptions],
        "perfectionist/sort-object-types": ["error", characterCodeSortOptions],
        "unicorn/catch-error-name": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-function-scoping": "error",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/filename-case": [
          "error",
          {
            case: "kebabCase",
            ignore: ["CHANGELOG.md", "README.md"],
          },
        ],
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-callback-reference": "error",
        "unicorn/no-array-for-each": "error",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-array-reduce": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-empty-file": "error",
        "unicorn/no-hex-escape": "error",
        "unicorn/no-instanceof-array": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-magic-array-flat-depth": "error",
        "unicorn/no-negated-condition": "error",
        "unicorn/no-new-array": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-null": ["off"],
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/no-process-exit": "error",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-typeof-undefined": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/no-zero-fractions": "error",
        "unicorn/numeric-separators-style": "error",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": ["error"],
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-dataset": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-event-target": ["error"],
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-native-coercion-functions": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-spread": "error",
        "unicorn/prefer-string-raw": "error",
        "unicorn/prefer-string-replace-all": ["error"],
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-top-level-await": "error",
        "unicorn/prefer-type-error": "error",
        "unicorn/relative-url-style": "error",
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/require-post-message-target-origin": "off",
        "unicorn/switch-case-braces": "error",
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
        "unicorn/prefer-module": "error",
        "unicorn/prefer-ternary": "error",
        "nextjs/google-font-display": ["off"],
        "typescript/strict-boolean-expressions": [
          "error",
          {
            allowNumber: false,
            allowString: false,
          },
        ],
        "array-func/prefer-array-from": ["off"],
        "formatjs/no-literal-string-in-jsx": ["error"],
        "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
        "import/extensions": [
          "error",
          "always",
          {
            cjs: "never",
            cts: "never",
            js: "never",
            jsx: "never",
            mjs: "never",
            mts: "never",
            ts: "never",
            tsx: "never",
          },
        ],
        "import/first": ["error"],
        "import/no-absolute-path": ["error"],
        "import/no-amd": ["error"],
        "import/no-anonymous-default-export": ["error"],
        "import/no-cycle": ["error"],
        "import/no-default-export": ["error"],
        "import/no-dynamic-require": ["error"],
        "import/no-empty-named-blocks": ["error"],
        "import/no-mutable-exports": ["error"],
        "import/no-self-import": ["error"],
        "import/prefer-default-export": ["off"],
        // TODO: import/no-deprecated: available in oxlint, enable when import plugin stabilizes
        // TODO: import/no-unresolved: not yet implemented in oxlint (needs module resolution)
        // TODO: import/no-extraneous-dependencies: not yet implemented in oxlint (needs module resolution)
        // TODO: import/no-useless-path-segments: not yet implemented in oxlint
        // TODO: import/newline-after-import: not yet implemented in oxlint
        // TODO: import/no-import-module-exports: not yet implemented in oxlint
        // TODO: import/no-unused-modules: not yet implemented in oxlint
        // NOTE: unicorn/prevent-abbreviations: not implemented in oxlint; enforced via ESLint
        // NOTE: unicorn/better-regex: not implemented in oxlint; covered by eslint-plugin-regexp
        "promise/no-multiple-resolved": ["error"],
        "promise/prefer-await-to-callbacks": ["error"],
        "promise/prefer-await-to-then": ["error"],
        "@stylistic/jsx-newline": ["error", { prevent: true }],
        "@stylistic/lines-between-class-members": ["error", "always", { exceptAfterSingleLine: false }],
        "simple-import-sort/exports": ["error"],
        "simple-import-sort/imports": [
          "error",
          {
            groups: [[String.raw`^\u0000`, "^node:", String.raw`^@?\w`, "^", String.raw`^\.`]],
          },
        ],
        "sort-destructure-keys/sort-destructure-keys": ["error"],
        "unicorn/custom-error-definition": ["error"],
      },
      jsPlugins: [
        resolvePlugin("@eslint-community/eslint-plugin-eslint-comments"),
        resolvePlugin("eslint-plugin-regexp"),
        resolvePlugin("eslint-plugin-sonarjs"),
        resolvePlugin("eslint-plugin-perfectionist"),
        resolvePlugin("@stylistic/eslint-plugin"),
        resolvePlugin("eslint-plugin-canonical"),
        resolvePlugin("eslint-plugin-formatjs"),
        resolvePlugin("eslint-plugin-simple-import-sort"),
        resolvePlugin("eslint-plugin-sort-destructure-keys"),
        resolvePlugin("eslint-plugin-array-func"),
      ],
    },
    {
      files: ["**/*.cjs"],
      rules: {
        "typescript/no-var-requires": ["off"],
      },
    },
    {
      files: [
        "**/*.cjs",
        "**/*.js",
        "**/*.jsx",
        "**/*.mjs",
        "**/*.d.ts",
        "**/*.cts",
        "**/*.mts",
        "**/*.ts",
        "**/*.tsx",
      ],
      rules: {
        "json-schema-validator/no-invalid": ["error"],
      },
      jsPlugins: [resolvePlugin("eslint-plugin-json-schema-validator")],
    },
    {
      files: [
        "**/*.config.{cjs,js,jsx,mjs,cts,mts,ts,tsx}",
        "*.d.ts",
        // Next.js App Router and Pages Router convention files require default exports
        "**/src/app/**",
        "**/src/pages/**",
        // The request configuration module of next-intl
        "**/src/i18n/request.ts",
      ],
      rules: {
        "import/no-default-export": ["off"],
      },
    },
  ],
});
