[project]
name = "spear-ai-ruff-config"
version = "6.0.0"
authors = [{ name = "Spear AI", email = "org@spear.ai" }]
description = "Spear AI Ruff config"
keywords = [
  "ai",
  "config",
  "ruff",
  "spear"
]
requires-python = ">=3.10,<3.13"
dependencies = [
  "ruff~=0.12"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
