[tool.poetry]
name = "spear-ai-ruff-config"
version = "4.0.0"
description = "Spear AI Ruff config"
authors = ["Spear AI <org@spear.ai>"]
keywords = [
  "ai",
  "config",
  "ruff",
  "spear"
]
packages = [{ include = "spear_ai_ruff_config" }]
readme = "README.md"
repository = "https://github.com/spear-ai/citizen"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
ruff = "^0.3.7"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
